const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Vehicle = require('./models/Vehicle');
const User = require('./models/User');

dotenv.config();

mongoose.connect(process.env.MONGODB_URI, {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

const vehicles = [
  {
    title: '2022 Toyota Land Cruiser Prado',
    brand: 'Toyota',
    model: 'Land Cruiser Prado',
    year: 2022,
    mileage: 15000,
    price: 55000,
    bodyType: 'suv',
    fuelType: 'diesel',
    transmission: 'auto',
    driveType: '4WD',
    engineCapacity: '2.8L',
    color: 'White',
    condition: 'excellent',
    location: 'Tokyo, Japan',
    port: 'Yokohama',
    isFeatured: true,
    description: 'Pristine condition 2022 Land Cruiser Prado. Low mileage and well-maintained.',
    features: ['Leather Seats', 'Sunroof', 'Navigation', 'Backup Camera'],
  },
  {
    title: '2020 Honda CR-V EX-L',
    brand: 'Honda',
    model: 'CR-V',
    year: 2020,
    mileage: 35000,
    price: 28500,
    bodyType: 'suv',
    fuelType: 'gasoline',
    transmission: 'auto',
    driveType: 'AWD',
    engineCapacity: '1.5L Turbo',
    color: 'Silver',
    condition: 'good',
    location: 'Osaka, Japan',
    port: 'Kobe',
    isFeatured: true,
    description: 'Reliable family SUV with all the safety features.',
    features: ['Apple CarPlay', 'Blind Spot Monitor', 'Heated Seats'],
  },
  {
    title: '2019 BMW 3 Series 330i',
    brand: 'BMW',
    model: '3 Series',
    year: 2019,
    mileage: 42000,
    price: 32000,
    bodyType: 'sedan',
    fuelType: 'gasoline',
    transmission: 'auto',
    driveType: 'RWD',
    engineCapacity: '2.0L',
    color: 'Blue',
    condition: 'excellent',
    location: 'Munich, Germany',
    port: 'Hamburg',
    isFeatured: false,
    description: 'Sporty sedan with impressive performance and luxury interior.',
    features: ['Premium Sound', 'Parking Sensors', 'M Sport Package'],
  },
  {
    title: '2021 Mercedes-Benz GLC 300',
    brand: 'Mercedes-Benz',
    model: 'GLC',
    year: 2021,
    mileage: 22000,
    price: 45000,
    bodyType: 'suv',
    fuelType: 'gasoline',
    transmission: 'auto',
    driveType: 'AWD',
    engineCapacity: '2.0L',
    color: 'Black',
    condition: 'excellent',
    location: 'Stuttgart, Germany',
    port: 'Bremerhaven',
    isFeatured: true,
    description: 'Luxury compact SUV with modern tech and smooth ride.',
    features: ['Panoramic Roof', 'MBUX Infotainment', 'Ambient Lighting'],
  },
  {
    title: '2018 Ford Ranger Wildtrak',
    brand: 'Ford',
    model: 'Ranger',
    year: 2018,
    mileage: 65000,
    price: 24000,
    bodyType: 'truck',
    fuelType: 'diesel',
    transmission: 'auto',
    driveType: '4WD',
    engineCapacity: '3.2L',
    color: 'Orange',
    condition: 'good',
    location: 'Bangkok, Thailand',
    port: 'Laem Chabang',
    isFeatured: false,
    description: 'Tough and capable pickup truck ready for work or play.',
    features: ['Tow Bar', 'Roof Rails', 'Bed Liner'],
  },
  {
    title: '2023 Tesla Model 3 Long Range',
    brand: 'Tesla',
    model: 'Model 3',
    year: 2023,
    mileage: 8000,
    price: 48000,
    bodyType: 'sedan',
    fuelType: 'electric',
    transmission: 'auto',
    driveType: 'AWD',
    engineCapacity: 'Electric',
    color: 'Grey',
    condition: 'excellent',
    location: 'California, USA',
    port: 'Los Angeles',
    isFeatured: true,
    description: 'Nearly new Tesla Model 3 with long range battery and Autopilot.',
    features: ['Autopilot', 'Premium Audio', 'Heated Steering Wheel'],
  },
  {
    title: '2020 Toyota Corolla Hybrid',
    brand: 'Toyota',
    model: 'Corolla',
    year: 2020,
    mileage: 28000,
    price: 21500,
    bodyType: 'sedan',
    fuelType: 'hybrid',
    transmission: 'auto',
    driveType: 'FWD',
    engineCapacity: '1.8L',
    color: 'Red',
    condition: 'good',
    location: 'Tokyo, Japan',
    port: 'Yokohama',
    isFeatured: false,
    description: 'Fuel-efficient and reliable commuter car.',
    features: ['Hybrid System', 'Safety Sense', 'Smart Key'],
  },
  {
    title: '2022 Hyundai Tucson Premium',
    brand: 'Hyundai',
    model: 'Tucson',
    year: 2022,
    mileage: 18000,
    price: 29000,
    bodyType: 'suv',
    fuelType: 'gasoline',
    transmission: 'auto',
    driveType: 'FWD',
    engineCapacity: '2.5L',
    color: 'Dark Grey',
    condition: 'excellent',
    location: 'Seoul, South Korea',
    port: 'Incheon',
    isFeatured: false,
    description: 'Modern design with a comfortable interior and great tech.',
    features: ['Digital Key', 'Ventilated Seats', 'Wireless Charging'],
  },
  {
    title: '2019 Lexus RX 450h Luxury',
    brand: 'Lexus',
    model: 'RX',
    year: 2019,
    mileage: 45000,
    price: 42000,
    bodyType: 'suv',
    fuelType: 'hybrid',
    transmission: 'auto',
    driveType: 'AWD',
    engineCapacity: '3.5L V6',
    color: 'Blue',
    condition: 'excellent',
    location: 'Nagoya, Japan',
    port: 'Nagoya',
    isFeatured: true,
    description: 'Smooth and silent hybrid luxury SUV.',
    features: ['Mark Levinson Audio', '360 Camera', 'Heated/Cooled Seats'],
  },
  {
    title: '2021 Volkswagen Golf GTI',
    brand: 'Volkswagen',
    model: 'Golf',
    year: 2021,
    mileage: 15000,
    price: 34000,
    bodyType: 'sedan',
    fuelType: 'gasoline',
    transmission: 'auto',
    driveType: 'FWD',
    engineCapacity: '2.0L Turbo',
    color: 'Black',
    condition: 'excellent',
    location: 'Wolfsburg, Germany',
    port: 'Hamburg',
    isFeatured: false,
    description: 'The definitive hot hatch, exciting performance and daily usability.',
    features: ['Digital Cockpit', 'Adaptive Chassis', 'Tartan Seats'],
  },
  {
    title: '2018 Nissan X-Trail 4WD',
    brand: 'Nissan',
    model: 'X-Trail',
    year: 2018,
    mileage: 72000,
    price: 18500,
    bodyType: 'suv',
    fuelType: 'gasoline',
    transmission: 'auto',
    driveType: '4WD',
    engineCapacity: '2.5L',
    color: 'Silver',
    condition: 'good',
    location: 'Saitama, Japan',
    port: 'Yokohama',
    isFeatured: false,
    description: 'Practical SUV with 4WD capability and 7 seats.',
    features: ['7 Seats', 'Roof Rails', 'Bluetooth'],
  },
  {
    title: '2020 Mazda CX-5 Grand Touring',
    brand: 'Mazda',
    model: 'CX-5',
    year: 2020,
    mileage: 31000,
    price: 27000,
    bodyType: 'suv',
    fuelType: 'gasoline',
    transmission: 'auto',
    driveType: 'AWD',
    engineCapacity: '2.5L',
    color: 'Soul Red',
    condition: 'excellent',
    location: 'Hiroshima, Japan',
    port: 'Hiroshima',
    isFeatured: false,
    description: 'Stylish SUV with premium feel and engaging drive.',
    features: ['Bose Sound', 'Heads-up Display', 'Power Liftgate'],
  },
  {
    title: '2024 Kia Sorento HEV',
    brand: 'Kia',
    model: 'Sorento',
    year: 2024,
    mileage: 3000,
    price: 43000,
    bodyType: 'suv',
    fuelType: 'hybrid',
    transmission: 'auto',
    driveType: 'AWD',
    engineCapacity: '1.6L Turbo Hybrid',
    color: 'Snow White Pearl',
    condition: 'excellent',
    location: 'Seoul, South Korea',
    port: 'Incheon',
    isFeatured: true,
    description: 'Latest model Sorento with efficient hybrid powertrain.',
    features: ['Panoramic Sunroof', 'Blind Spot View Monitor', 'Smart Park'],
  },
  {
    title: '2019 Audi A4 Premium Plus',
    brand: 'Audi',
    model: 'A4',
    year: 2019,
    mileage: 38000,
    price: 29500,
    bodyType: 'sedan',
    fuelType: 'gasoline',
    transmission: 'auto',
    driveType: 'AWD',
    engineCapacity: '2.0L Turbo',
    color: 'Manhattan Grey',
    condition: 'excellent',
    location: 'Ingolstadt, Germany',
    port: 'Bremerhaven',
    isFeatured: false,
    description: 'Elegant executive sedan with Quattro all-wheel drive.',
    features: ['Virtual Cockpit', 'Bang & Olufsen Sound', 'Matrix LED'],
  },
  {
    title: '2021 Mitsubishi L200 Barbarian',
    brand: 'Mitsubishi',
    model: 'L200',
    year: 2021,
    mileage: 26000,
    price: 31000,
    bodyType: 'truck',
    fuelType: 'diesel',
    transmission: 'auto',
    driveType: '4WD',
    engineCapacity: '2.2L',
    color: 'Electric Blue',
    condition: 'excellent',
    location: 'Kyoto, Japan',
    port: 'Osaka',
    isFeatured: false,
    description: 'Fully loaded pickup with great off-road ability.',
    features: ['Leather Seats', '360 View', 'Off-road Mode'],
  },
  {
    title: '2022 Subaru Forester Sport',
    brand: 'Subaru',
    model: 'Forester',
    year: 2022,
    mileage: 12000,
    price: 33000,
    bodyType: 'suv',
    fuelType: 'gasoline',
    transmission: 'auto',
    driveType: 'AWD',
    engineCapacity: '2.5L Boxer',
    color: 'Magnetite Gray',
    condition: 'excellent',
    location: 'Gunma, Japan',
    port: 'Yokohama',
    isFeatured: true,
    description: 'Reliable AWD SUV with EyeSight safety technology.',
    features: ['EyeSight', 'X-Mode', 'Sport Trim'],
  },
  {
    title: '2018 Volvo XC90 T6 Inscription',
    brand: 'Volvo',
    model: 'XC90',
    year: 2018,
    mileage: 58000,
    price: 37000,
    bodyType: 'suv',
    fuelType: 'gasoline',
    transmission: 'auto',
    driveType: 'AWD',
    engineCapacity: '2.0L Turbo & Supercharged',
    color: 'Crystal White',
    condition: 'good',
    location: 'Gothenburg, Sweden',
    port: 'Gothenburg',
    isFeatured: false,
    description: 'Luxury 7-seater SUV focused on safety and Swedish design.',
    features: ['Nappa Leather', 'Pilot Assist', 'Harman Kardon Audio'],
  },
  {
    title: '2020 Land Rover Defender 110',
    brand: 'Land Rover',
    model: 'Defender',
    year: 2020,
    mileage: 33000,
    price: 68000,
    bodyType: 'suv',
    fuelType: 'diesel',
    transmission: 'auto',
    driveType: '4WD',
    engineCapacity: '2.0L D240',
    color: 'Pangea Green',
    condition: 'excellent',
    location: 'London, UK',
    port: 'Southampton',
    isFeatured: true,
    description: 'The iconic off-roader reborn with modern comfort and capability.',
    features: ['Air Suspension', 'Tow Pack', 'Pivi Pro'],
  },
  {
    title: '2023 BYD Atto 3 Extended',
    brand: 'BYD',
    model: 'Atto 3',
    year: 2023,
    mileage: 5000,
    price: 36000,
    bodyType: 'suv',
    fuelType: 'electric',
    transmission: 'auto',
    driveType: 'FWD',
    engineCapacity: 'Electric',
    color: 'Surf Blue',
    condition: 'excellent',
    location: 'Shenzhen, China',
    port: 'Shenzhen',
    isFeatured: true,
    description: 'Modern electric SUV with innovative interior and great range.',
    features: ['Rotating Screen', 'V2L Capability', 'Blade Battery'],
  },
  {
    title: '2019 Toyota Hiace Commuter',
    brand: 'Toyota',
    model: 'Hiace',
    year: 2019,
    mileage: 85000,
    price: 32000,
    bodyType: 'van',
    fuelType: 'diesel',
    transmission: 'manual',
    driveType: 'RWD',
    engineCapacity: '2.8L',
    color: 'White',
    condition: 'good',
    location: 'Toyota City, Japan',
    port: 'Nagoya',
    isFeatured: false,
    description: 'Versatile 15-seater passenger van, extremely durable.',
    features: ['Air Conditioning', 'Power Steering', 'Reverse Sensors'],
  },
  {
    title: '2021 Porsche Macan S',
    brand: 'Porsche',
    model: 'Macan',
    year: 2021,
    mileage: 18000,
    price: 62000,
    bodyType: 'suv',
    fuelType: 'gasoline',
    transmission: 'auto',
    driveType: 'AWD',
    engineCapacity: '2.9L V6 Turbo',
    color: 'Sapphire Blue',
    condition: 'excellent',
    location: 'Stuttgart, Germany',
    port: 'Bremerhaven',
    isFeatured: true,
    description: 'High-performance compact luxury SUV.',
    features: ['Sport Chrono', 'PASM', 'Leather Interior'],
  }
];

const seedDB = async () => {
  try {
    await Vehicle.deleteMany({});
    await Vehicle.insertMany(vehicles);
    console.log('Database Seeded Successfully');
    process.exit();
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
};

seedDB();
